config/routes.rb
Rails.application.routes.draw do
  devise_for :users #, controllers: { registrations: "registrations" }
  root to: 'pages#home'

  resources :programs do
    member do
      put 'like', to: 'programs#like', as: 'like'
      put 'unlike', to: 'programs#unlike', as: 'unlike'
    end
    resources :applications, except: :index
  end

  get '/search' => 'search#index'

  get 'about', to: 'pages#about', as: 'about'
  get 'help', to: 'pages#help', as: 'help'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'business_dashboard',
      to: 'pages#business_dashboard',
      as: 'business_dashboard'
  get 'user_dashboard', to: 'pages#user_dashboard', as: 'user_dashboard'
  get 'team', to: 'pages#team', as: 'team'
  get 'blog', to: 'pages#blog', as: 'blog'
  get 'career', to: 'pages#career', as: 'career_options'
  get 'businesses', to: 'pages#businesses', as: 'businesses'
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :program
  belongs_to :user

  enum status: { pending: 0, interested: 1, rejected: 2, accepted: 3 }, _default: "pending"

  validates :first_essay, length: {minimum: 50, maximum: 1500}, presence: true, if: :essay_one?
  validates :second_essay, length: {minimum: 50, maximum: 1500}, presence: true, if: :essay_two?
  validates :third_essay, length: {minimum: 50, maximum: 1500}, presence: true, if: :essay_three?

  def essay_one?
    return true if self.program.essay_one_needed
  end

  def essay_two?
    return true if self.program.essay_two_needed
  end

  def essay_three?
    return true if self.program.essay_three_needed 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pagy::Backend


  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :organization_name, :location, :bio, :age, :goal, :employer, :admin, :user_type, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :organization_name, :location, :bio, :age, :goal, :employer, :admin, :user_type, :photo])
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_program, only: %i[show edit update destroy new create]
  # before action :set_application, only: %i[show edit update destroy]
  # before action :set_application, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]


  def new
    @program = Program.find(params[:program_id])
    @application = Application.new
  end
  
  def create
    @program = Program.find(params[:program_id])
    @application = Application.new(application_params)
    @application.essay_question_one = @program.essay_question_one #if @program.essay_one_needed
    @application.essay_question_two = @program.essay_question_two# if @program.essay_two_needed
    @application.essay_question_three = @program.essay_question_three# if @program.essay_three_needed
    @application.user_id = current_user.id
    @application.program = @program
    if @application.save
      flash[:notice] = "You've successfully submitted your application!"
      redirect_to @program
    else
      flash[:notice] = "There was an error, please try again!"
      render 'new'
      # render new_program_application_path(@program, @application)
      raise
    end
  end

  def edit
    @application = Application.find(params[:id])
  end

  def update
    @application = Application.find(params[:id])
    if @application.update(application_params)
      flash[:notice] = "You've successfully updated your application"
      redirect_to user_dashboard_path
    else
      flash[:error] = 'There was an error, please try again!'
      render 'edit'
    end
  end

  def show
    @application = Application.find(params[:id])
  end

  def destroy
    @application = Application.find(params[:id])
    @application.destroy
    flash[:notice] = 'Your application was successfully deleted!'
    redirect_to @application.program
  end

  private

  def set_program
    @program = Program.find(params[:program_id])
  end

  def set_application
    @application = Application.find(params[:id])
  end

  def application_params
    params
      .require(:application)
      .permit(
        :essay_question_one,
        :first_essay,
        :essay_question_two,
        :second_essay,
        :essay_question_three,
        :third_essay,
        :status,
        :program_id,
        :user_id, 
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/applications/_application_user_dashboard_card.html.erb
<p><%= application.program.title %></p>

app/views/applications/edit.html.erb
<div class="row align-items-center justify-content-center">
  <div class="col-sm-8 card p-4 m-4 bg-light ">
    <h2>Apply to your dream program and improve your career</h2>
    <%= simple_form_for [@program, @application], url: program_applications_path, method: :post do |f|%>
      <p>Upon applying, the program manager will receive your personal information and subsequently decide upon your application as soon as they can</p>
      <div id="application_personal_details">
        <%= current_user.first_name %>
      </div>
      <% if @program.essay_one_needed? %>
        <div id="application_essay_one">
          <%= f.input :first_essay, label: "Applications to this program require an essay or more to be considered.  The program requires you to answer the following essay question: #{@program.essay_question_one}",  
      placeholder: "Please write your first essay response in here" %>
        </div>
      <% end %>
      <% if @program.essay_two_needed? %>
        <div id="application_essay_two" >
          <%= f.input :second_essay, label: "The program requires you to also answer the following essay question: #{@program.essay_question_two}", 
      placeholder: "Please write your second essay response in here" %>
        </div>
      <% end %>
      <% if @program.essay_three_needed? %>
        <div id="application_essay_three" >
          <%= f.input :third_essay, label: "The program requires you to also answer the following essay question: #{@program.essay_question_three}", 
      placeholder: "Please write your final essay response in here" %>
        </div>
      <% end %>
      <%= f.input :status, value: :pending, as: :hidden %>
      <div style="text-align:center">
        <%= f.button :submit, 'Submit', class: 'btn btn-primary'%>
      </div>
    <% end %>
  </div>
</div>

app/views/applications/new.html.erb
<div class="row align-items-center justify-content-center">
  <div class="col-sm-8 card p-4 m-4 bg-light ">
    <h2>Apply to your dream program and improve your life</h2>
    <%= simple_form_for [@program, @application], url: program_applications_path, method: :post do |f|%>
      <p>Upon applying, the program manager will receive the following personal information about you before subsequently deciding upon your application as soon as they can</p>
      <div id="application_personal_details">
        <%= current_user.first_name %>
      </div>
      <% if @program.essay_one_needed? %>
        <div id="application_essay_one">
          <%= f.input :first_essay, label: "Applications to this program require an essay or more to be considered.  The program requires you to answer the following essay question: #{@program.essay_question_one}",  
      placeholder: "Please write your first essay response in here" %>
        </div>
      <% end %>
      <% if @program.essay_two_needed? %>
        <div id="application_essay_two" >
          <%= f.input :second_essay, label: "The program requires you to also answer the following essay question: #{@program.essay_question_two}", 
      placeholder: "Please write your second essay response in here" %>
        </div>
      <% end %>
      <% if @program.essay_three_needed? %>
        <div id="application_essay_three" >
          <%= f.input :third_essay, label: "The program requires you to also answer the following essay question: #{@program.essay_question_three}", 
      placeholder: "Please write your final essay response in here" %>
        </div>
      <% end %>
      <%= f.input :status, value: :pending, as: :hidden %>
      <div style="text-align:center">
        <%= f.button :submit, 'Submit', class: 'btn btn-primary'%>
      </div>
    <% end %>
  </div>
</div>

app/views/applications/show.html.erb
-Pundit to restrict access.
-Private information of applicant.
-Questions from proper controller actions.
-User dashboard AJAX access like program index show combo.
-