config/routes.rb
Rails.application.routes.draw do
  devise_for :users #, controllers: { registrations: "registrations" }
  root to: 'pages#home'

  resources :programs do
    member do
      put 'like', to: 'programs#like', as: 'like'
      put 'unlike', to: 'programs#unlike', as: 'unlike'
    end
    resources :applications, except: :index
  end

  get '/search' => 'search#index'

  get 'about', to: 'pages#about', as: 'about'
  get 'help', to: 'pages#help', as: 'help'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'business_dashboard',
      to: 'pages#business_dashboard',
      as: 'business_dashboard'
  get 'user_dashboard', to: 'pages#user_dashboard', as: 'user_dashboard'
  get 'team', to: 'pages#team', as: 'team'
  get 'blog', to: 'pages#blog', as: 'blog'
  get 'career', to: 'pages#career', as: 'career_options'
  get 'businesses', to: 'pages#businesses', as: 'businesses'
end

app/models/program.rb
class Program < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  #  I had to do inverse of and accepts nested to let applications access program parent attributes for its validations
  has_many :applications, inverse_of: :program
  accepts_nested_attributes_for :applications
  acts_as_votable
  acts_as_taggable_on :occupation_taggings

  validates :title, presence: true, length: { minimum: 10 }
  validates :headline, presence: true, length: { minimum: 10 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1500 }
  validates :application_due_date, presence: true, if: :rolling?
  validates :start_date, presence: true, if: :rolling?
  validates :location, presence: true
  validates :spots, presence: true
  validates :requirements, presence: true, length: { minimum: 10 }
  validates :length, presence: true
  validates :minimum_age, presence: true, numericality: { only_integer: true,  greater_than: 12 }
  validates :visa_sponsorship, inclusion: [true, false], exclusion: [nil]
  validates :virtual_components, inclusion: [true, false], exclusion: [nil]
  validates :housing_provided, inclusion: [true, false], exclusion: [nil]
  validates :essay_one_needed, inclusion: [true, false], exclusion: [nil]
  validates :essay_two_needed, inclusion: [true, false], exclusion: [nil]
  validates :essay_three_needed, inclusion: [true, false], exclusion: [nil]
  validates :essay_question_one, presence: true, if: :essay_one?
  validates :essay_question_two, presence: true, if: :essay_two?
  validates :essay_question_three, presence: true, if: :essay_three?
  validates :salary, inclusion: [true, false], exclusion: [nil]
  validates :salary_paid, presence: true, if: :salary?
  validates :cost, presence: true
  validates :certificate_awarded, inclusion: [true, false], exclusion: [nil]
  validates :nationals_only, inclusion: [true, false], exclusion: [nil]
  # validates :active, inclusion: [true, false], exclusion: [nil]
  validates :time_requirement, presence: true
  validates :job_guaranteed, inclusion: [true, false], exclusion: [nil]
  # validates :career_category, presence: true
  validates :program_format, presence: true
  validates :relocation_assistance, inclusion: [true, false], exclusion: [nil]
  # validates :application_due_date, :future_date
  validate :future_date_application?
  validate :future_date_start?, if: :rolling?
  validates :occupation_tagging_list, presence: true

  enum status: { Active: 0, Temporarily_paused: 1, Permanently_closed: 2 }, _default: "Active"

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

    pg_search_scope :global_search,
    against: [ :program_format, :length, :remote, :location, :time_requirement ],
      associated_against: {
        occupation_taggings: [:name],
    },
    using: {
      tsearch: { prefix: true }
    }

  def self.career_category
    ['Air conditioning and heating', 'Carpeting', 'Construction', 'Food prep', 'Health care and medicine', 'Hospitality', 'HVAC', 'IT', 'Military', 'Software engineering', 'Manufacturing', 'Aerospace', 'Merchandising', 'Sales', 'Marketing', 'Accounting', 'Law/legal', 'Law enforcement',  ]
  end

  def self.program_format
    ['Internship', 'Apprenticeship', 'Certification program', 'Degree', 'Remote program', 'Class', 'Workshop', 'Shadowing program' ]
  end

  def self.length
    ['Less than one week', '1-2 weeks', '2-4 weeks', '1 month', '1-2 months', '2-3 months', '3-6 months', '6-12 months', '12-18 months', '18-24 months', '24-36 months', '36+ months']
  end

  def self.time_requirement
    ['Part-time', 'Full-time', 'Varies']
  end

  def active
    @programs = Program.where(status: "Active")
  end

  def salary?
    return true if salary == true
  end

  def essay_one?
    return true if essay_one_needed == true
  end

  def essay_two?
    return true if essay_two_needed == true
  end

  def essay_three?
    return true if essay_three_needed == true
  end

  def rolling?
    return true if rolling == false
  end

  def future_date_application?
    if application_due_date < Date.today
      errors.add(:application_due_date, "The due date must be in the future!")
    end
  end

  def future_date_start?
    if start_date < Date.today
      errors.add(:start_date, "The start date must be in the future!")
    end
  end

  # scopes?

  # def auto_finish
  #   if application_due_date > Date.today
  #     @program.status.Permanently_closed!
  #     ...set this up as a que job for later.
  #   end
  # end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: %i[show edit update destroy like unlike]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    # params["search"].values !!!
    # multiple values on art project was concacetannating arrays, but one is a string...so concat won't work!  FUCK!
    if params["search"].present? && params["search"]["location"].present?
      @filter = [params[:search][:location], params[:search][:remote], params[:search][:length], params[:search][:program_format], params[:search][:occupation_tagging_list], params[:search][:time_requirement]].reject(&:blank?)
      
      @pagy, @programs = pagy(Program.global_search(@filter).where(status: :Active).includes([:user]).near(params["search"]["location"]), items: 20)
    elsif params["search"].present? 
      @filter = [params[:search][:location], params[:search][:remote], params[:search][:length], params[:search][:program_format], params[:search][:occupation_tagging_list], params[:search][:time_requirement]].reject(&:blank?)

      @pagy, @programs = pagy(Program.global_search(@filter).where(status: :Active).includes([:user]), items: 20)
    else
      @pagy, @programs = pagy(Program.where(status: :Active).includes([:user]), items: 20)
    end
    respond_to do |format|
      format.html
      format.js #{ render layout: false }
    end
    # raise
    @programs_size = Program.where(status: :Active)
  end

  def new
    @program = Program.new
  end

  def create
    @program = Program.new(program_params)
    if @program.save
      flash[:notice] = 'Your program was successfully created!'
      redirect_to @program
    else
      flash[:error] = 'There was an error, please try again!'
      render 'new'
    end
    # raise
  end

  def show
    respond_to do |format|
      format.html { render 'programs/show' }
      format.js { render layout: false } # Add this line to you respond_to block
    end
  end

  def update
    if @program.update(program_params)
      flash[:notice] = "You've successfully updated your program!"
      redirect_to @program # or dashboard?
    else
      flash[:error] = 'There was an error, please try again!'
      render 'edit'
    end
  end

  def destroy
    @program.destroy
    flash[:notice] = 'This program was successfully deleted!'
    redirect_to business_dashboard_path
  end

  def edit
   
  end

  def like
    @program.liked_by current_user
    flash[:notice] = "You've successfully liked this program, find it in your dashboard to easily apply to later"
      respond_to do |format|
        format.html { redirect_to @program }
        format.js { render layout: false  }
      end
  end

  def unlike
    @program.unliked_by current_user
    flash[:notice] = "You've successfully unliked this program"
    respond_to do |format|
      format.html { redirect_to @program }
      format.js { render layout: false }
    end
  end

  private

  def set_program
    @program = Program.find(params[:id])
  end

  def program_params
    params
      .require(:program)
      .permit(
        :title,
        :headline,
        :description,
        :rolling,
        :application_due_date,
        :location,
        :remote,
        :spots,
        :requirements,
        :length,
        :minimum_age,
        :visa_sponsorship,
        :start_date,
        :virtual_components,
        :housing_provided,
        :essay_question_one,
        :essay_question_two,
        :essay_question_three,
        :salary,
        :salary_paid,
        :cost,
        :certificate_awarded,
        :nationals_only,
        :time_requirement,
        :job_guaranteed,
        :relocation_assistance,
        :essay_one_needed,
        :essay_two_needed,
        :essay_three_needed,
        :status,
        :program_format,
        :occupation_tagging_list,
        :search
      )
  end
end

app/views/programs/_program_card_index.html.erb
<div class="card-program">
  <%= cl_image_tag program.user.photo.key, height: 300, width: 400, crop: :fill, :alt=>"Business Logo" %>
  <div class="card-program-infos">
    <h2><%= program.title %></h2>
    <p><%= program.headline %></p>
    <p><%= program.description %></p>
    <p><%= program.location %></p>
    <p><%= link_to 'Show', program, remote: true %></p>
  </div>
</div>

app/views/programs/_show.html.erb
<div class="section">
  <div class="container p-2">
    <div class="row">
      <div class="col">
        <%= cl_image_tag program.user.photo.key, height: 150, width: 200, crop: :fill, :alt=>"Business Logo" %>
        <h2> <%= @program.title %> </h2>
        <p> <%= @program.headline %> </p>
        <p>Type of program: <%= @program.program_format %> </p>
        <p>Description of the program: <%= @program.description %> </p>
        <p>Location: <%= @program.location %> </p>
        <p>Number of spots available: <%= @program.spots %> </p>
        <p>Requirements for applicants: <%= @program.requirements %> </p>
        <p>Length of program: <%= @program.length %> </p>
        <p>Minimum age required for applicants: <%= @program.minimum_age %> </p>
        <p>Program cost: <%= @program.cost %> </p>
        <p>Program time commitment: <%= @program.time_requirement %> </p>
        <p>Tag check: <%= @program.occupation_tagging_list.each do |tag| %></p>
          <%= link_to tag, programs_path(tag: tag) %>
        <% end %>
        <% if current_user %>
          <div class="container">
            <div class="row py-2">
              <div class="col">
                <div class="favorites", id="favorite_buttons">
                  <% if !current_user.find_liked_items.include?(@program) %>
                    <div id="favorite_button">
                      <%= link_to 'Save this program for later', like_program_path(@program), remote: true, method: :put, class: 'btn btn-primary', id: "like_button" %>
                    </div>
                  <% end %>
                  <% if current_user.find_liked_items.include?(@program) %>
                    <div id="unfavorite_button">
                      <%= link_to 'Unsave this program', unlike_program_path(@program), remote: true, method: :put, class: 'btn btn-primary', id: "unlike_button" %>
                    </div>
                  <% end %>
                </div>
                <div class="col">
                  <%= link_to 'Apply to this program', new_program_application_path(@program, @application), class: 'btn btn-primary' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/programs/edit.html.erb
<div class="container">
  <div class="row align-items-center justify-content-center">
    <div class="col-sm-8 card p-4 m-4 bg-light ">
      <h2>Create your program so that potential students can apply</h2>
      <p>Please provide the following details about your program</p>
      <%= simple_form_for @program do |f|%>
        <%#= f.input :career_category, label: "Please pick the career category that best applies to this program", collection: Program.career_category %>
        <%= f.input :occupation_tagging_list, collection: Program.career_category, label: "Please pick the career category that best applies to this program" %>
        <%= f.input :program_format, label: "Please pick the format that best applies to this program", collection: Program.program_format %>
        <%= f.input :title, label:  "What would you like to name your program?", placeholder: "4-week long carpeting crash course" %>
        <%= f.input :headline, label: "Provide a one sentence summary about your program to garner interest", placeholder: "Learn carpeting basics 101" %>
        <%= f.input :description, label: "Provide an in-depth description about what your program has to offer potential students", placeholder: "We're offering a four-week long crash course for students to learn about the basics of carpeting.  It's a full-time class of four located in the heart of New York City.  No experience is necessary, must be at least 18, etc." %>
        <%= f.input :requirements, label: "What are the requirements that applicants need to have in order to apply successfully?", placeholder: 'There are no pre-requisites other than having enthusiasm to learn!' %>
        <div id="geocoder" >
          <%= f.input :location, label: "Where is this program located?", placeholder: "1 Rodeo Drive Beverly Hills California", input_html: { data: { geocoder_target: "location" }, class: "d-none" }, wrapper_html: { id: :location_label } %>
        </div>
        <pre id="result", class="d-none" ></pre>
        <%= f.input :rolling, label: "Are potential students allowed to apply at anytime?  Or is there a specific due date?" %>
        <div id="rolling_prompt" style="display:none">
          <%= f.input :application_due_date, label: "On what day are applications due by at the latest?", required: true %>
          <%= f.input :start_date, label: "On what date does this program begin?", required: true %>
        </div>
        <%= f.input :time_requirement, label: "What's the weekly time commitment for the program?", collection: Program.time_requirement %>
        <%= f.input :spots, label: "How many spots are there available for your program?", placeholder: "10" %>
        <%= f.input :length, collection: Program.length, label: "How long does the program last for?" %>
        <%= f.input :minimum_age, label: "What's the minimum age requirement for applicants?", placeholder: "16" %>
        <%= f.input :essay_one_needed, label: "Do you want applicants to submit an essay to be considered for admission?" %>
        <div id="first_essay_prompt" style="display:none">
          <%= f.input :essay_question_one, label: "What would you like the first essay to be about?", placeholder: "Why are you interested in our program?" %>
          <%= f.input :essay_two_needed, label: "Do you want applicants to submit a second essay as well?" %>
        </div>
        <div id="second_essay_prompt" style="display:none">
          <%= f.input :essay_question_two, label: "What would you like the second essay to be about?", placeholder: "What are your goals with regards to this program?" %>
          <%= f.input :essay_three_needed, label: "Do you want applicants to submit a third essay too?" %>
        </div>
        <div id="third_essay_prompt" style="display:none">
          <%= f.input :essay_question_three, label: "What would you like the third essay to be about?", placeholder: "Tell me about how you overcame a hardship that you've faced in the past?" %>
        </div>
        <%= f.input :salary, label: "Do you offer a salary or stipend for living expenses to program participants?" %>
        <div id="salary_prompt" style="display:none">
          <%= f.input :salary_paid, label: "What is the salary/stipend you have to offer?", placeholder: "$1000 per month" %>
        </div>
        <%= f.input :cost, label: "How much will it cost successful applicants to participate in and complete the program?", placeholder: "$2500" %>
        <%= f.input :nationals_only, label: "Are national citizens only eligible to apply?" %>
        <div id="visa_prompt" style="display:block">
          <%= f.input :visa_sponsorship, label: "Do you offer visa sponsorship for foreign nationals?" %>
        </div>
        <%= f.input :remote, label: "Is the program completely remote?" %>
        <%= f.input :virtual_components, label: "Are there any virtual or remote components for this program?" %>
        <%= f.input :housing_provided, label: "Would program participants have housing provided for them from you?" %>
        <%= f.input :relocation_assistance, label: "Will you provide participants with any help to relocate to the destination of your program?" %>
        <%= f.input :certificate_awarded, label: "Do participants earn any certification or degree upon completion?" %>
        <%= f.input :status, value: :Active, as: :hidden %>
        <%= f.input :job_guaranteed, label: "Are participants guaranteed to get a job with your organization upon successfully completing the program?" %>
        <div style="text-align:center">
          <%= f.button :submit, 'Submit', class: 'btn btn-primary'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/programs/index.html.erb
<section class="program-index-search">
  <div class="container">
    <div class="row align-items-center justify-content-center">
      <div class="col-sm-11 card p-2 m-2 bg-light ">
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
          Search and filter through programs
        </button>
        <div class="collapse" id="collapseExample">
          <div class="card card-body">
            <%= simple_form_for :search, url: programs_path, method: "GET", remote: true do |f| %>
              <div class="row row-cols-lg-auto g-3">
                <div id="geocoder" >
                  <%= f.input :location, label: "Where are you looking for a program?", required: false, wrapper_html: { id: :location_label }, input_html: { data: { geocoder_target: "location" }  }, as: :hidden %>
                  <pre id="result", class="d-none" ></pre>
                </div>
              </div>
              <%= f.input :remote, as: :select, label: "Do you want a remote only program?", required: false %>
              <%= f.input :length, label: "Would you like to filter by the program's length?", collection: Program.length, required: false %>
              <%= f.input :program_format, label: "What kind of program are you looking for?", collection: Program.program_format, required: false %>
              <%= f.input :time_requirement, label: "Would you like to filter by time requirement?", collection: Program.time_requirement, required: false %>
              <%= f.input :occupation_tagging_list, label: "What type of career category are you looking for?", collection: Program.career_category, required: false %>
              <%= f.submit 'Submit', class: 'btn btn-primary'%>
              <%= link_to "Reset", programs_path %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="program-index-cards">
  <div class="container">
    <div class="row">
      <div class="col-12 col-lg-5">
        <div id="programs_length">
          <p><%= @programs.length %> matching programs available of <%= @programs_size.length %> programs</p>
        </div>
        <div id="programs">
          <% @programs.each do |program| %>
            <%= render partial: 'programs/program_card_index', locals: {program: program} %>
          <% end %>
        </div>
        <%== pagy_bootstrap_nav(@pagy) %>
      </div>
      <div id="current_program", class="col-12 col-lg-7 card border">
      </div>
    </div>
  </div>
</section>

app/views/programs/index.js.erb
function searchPrograms(program) {
const programs = document.getElementById('programs');
programs.insertAdjacentHTML("beforeend", program);
} 

document.getElementById('programs').innerHTML = "";

<% @programs.each do |program| %>
searchPrograms("<%= escape_javascript(render partial: 'programs/program_card_index', locals: { program: program } ) %>"); 
<% end %>

document.getElementById("programs_length").innerHTML = ('<p><%= @programs.length %> matching programs available of <%= @programs_size.length %> programs</p>');

app/views/programs/like.js.erb
var favoriteButton = document.getElementById("favorite_buttons");

favoriteButton.innerHTML = (' <%= link_to 'Unsave this program',  unlike_program_path(@program), remote: true, method: :put, class: 'btn btn-primary', id: "unlike_button" %>');

app/views/programs/new.html.erb
<div class="container">
  <div class="row align-items-center justify-content-center">
    <div class="col-sm-8 card p-4 m-4 bg-light ">
      <h2>Create your program so that potential students can apply</h2>
      <p>Please provide the following details about your program</p>
      <%= simple_form_for @program do |f|%>
        <%#= f.input :career_category, label: "Please pick the career category that best applies to this program", collection: Program.career_category %>
        <%= f.input :occupation_tagging_list, collection: Program.career_category, label: "Please pick the career category that best applies to this program" %>
        <%= f.input :program_format, label: "Please pick the format that best applies to this program", collection: Program.program_format %>
        <%= f.input :title, label:  "What would you like to name your program?", placeholder: "4-week long carpeting crash course" %>
        <%= f.input :headline, label: "Provide a one sentence summary about your program to garner interest", placeholder: "Learn carpeting basics 101" %>
        <%= f.input :description, label: "Provide an in-depth description about what your program has to offer potential students", placeholder: "We're offering a four-week long crash course for students to learn about the basics of carpeting.  It's a full-time class of four located in the heart of New York City.  No experience is necessary, must be at least 18, etc." %>
        <%= f.input :requirements, label: "What are the requirements that applicants need to have in order to apply successfully?", placeholder: 'There are no pre-requisites other than having enthusiasm to learn!' %>
        <div id="geocoder" >
          <%= f.input :location, label: "Where is this program located?", placeholder: "1 Rodeo Drive Beverly Hills California", input_html: { data: { geocoder_target: "location" }, class: "d-none" }, wrapper_html: { id: :location_label } %>
        </div>
        <pre id="result", class="d-none" ></pre>
        <%= f.input :rolling, label: "Are potential students allowed to apply at anytime?  Or is there a specific due date?" %>
        <div id="rolling_prompt" style="display:none">
          <%= f.input :application_due_date, label: "On what day are applications due by at the latest?", required: true %>
          <%= f.input :start_date, label: "On what date does this program begin?", required: true %>
        </div>
        <%= f.input :time_requirement, label: "What's the weekly time commitment for the program?", collection: Program.time_requirement %>
        <%= f.input :spots, label: "How many spots are there available for your program?", placeholder: "10" %>
        <%= f.input :length, collection: Program.length, label: "How long does the program last for?" %>
        <%= f.input :minimum_age, label: "What's the minimum age requirement for applicants?", placeholder: "16" %>
        <%= f.input :essay_one_needed, label: "Do you want applicants to submit an essay to be considered for admission?" %>
        <div id="first_essay_prompt" style="display:none">
          <%= f.input :essay_question_one, label: "What would you like the first essay to be about?", placeholder: "Why are you interested in our program?" %>
          <%= f.input :essay_two_needed, label: "Do you want applicants to submit a second essay as well?" %>
        </div>
        <div id="second_essay_prompt" style="display:none">
          <%= f.input :essay_question_two, label: "What would you like the second essay to be about?", placeholder: "What are your goals with regards to this program?" %>
          <%= f.input :essay_three_needed, label: "Do you want applicants to submit a third essay too?" %>
        </div>
        <div id="third_essay_prompt" style="display:none">
          <%= f.input :essay_question_three, label: "What would you like the third essay to be about?", placeholder: "Tell me about how you overcame a hardship that you've faced in the past?" %>
        </div>
        <%= f.input :salary, label: "Do you offer a salary or stipend for living expenses to program participants?" %>
        <div id="salary_prompt" style="display:none">
          <%= f.input :salary_paid, label: "What is the salary/stipend you have to offer?", placeholder: "$1000 per month" %>
        </div>
        <%= f.input :cost, label: "How much will it cost successful applicants to participate in and complete the program?", placeholder: "$2500" %>
        <%= f.input :nationals_only, label: "Are national citizens only eligible to apply?" %>
        <div id="visa_prompt" style="display:block">
          <%= f.input :visa_sponsorship, label: "Do you offer visa sponsorship for foreign nationals?" %>
        </div>
        <%= f.input :remote, label: "Is the program completely remote?" %>
        <%= f.input :virtual_components, label: "Are there any virtual or remote components for this program?" %>
        <%= f.input :housing_provided, label: "Would program participants have housing provided for them from you?" %>
        <%= f.input :relocation_assistance, label: "Will you provide participants with any help to relocate to the destination of your program?" %>
        <%= f.input :certificate_awarded, label: "Do participants earn any certification or degree upon completion?" %>
        <%= f.input :status, value: :Active, as: :hidden %>
        <%= f.input :job_guaranteed, label: "Are participants guaranteed to get a job with your organization upon successfully completing the program?" %>
        <div style="text-align:center">
          <%= f.button :submit, 'Submit', class: 'btn btn-primary'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/programs/show.html.erb
<div class="container card my-2 align-items-center ">
  <div class="row ">
    <div class="col-12 col-lg-10">
      <%= render partial: 'programs/show', locals: {program: @program} %>
    </div>
  </div>
</div>

app/views/programs/show.js.erb
var currentProgram = document.querySelector("#current_program");
var indexSavedProgram = document.querySelector("#index_saved_programs");

if (currentProgram) {
document.querySelector("#current_program").innerHTML = ("<%= escape_javascript(render partial: 'programs/show', locals: { program: @program } ) %>");
} else {
document.querySelector("#index_saved_programs").innerHTML = ("<%= escape_javascript(render partial: 'programs/show', locals: { program: @program } ) %>");
}

app/views/programs/unlike.js.erb
var unfavoriteButton = document.getElementById("favorite_buttons");

unfavoriteButton.innerHTML = (' <%= link_to 'Save this program for later', like_program_path(@program), remote: true, method: :put, class: 'btn btn-primary', id: "like_button" %>');